# docker-compose.yml
services:
  # Database service
  db:
    image: postgres:14
    container_name: document_system_db
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-documents_db}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - document_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: document_system_app
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_NAME: ${DB_NAME:-documents_db}
      DB_PORT: 5432
      DB_SSLMODE: ${DB_SSLMODE:-disable}
      SERVER_PORT: 8080
    ports:
      - "${SERVER_PORT:-8080}:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - document_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  document_network:
    driver: bridge

